import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'chat_screen.dart';

class CoursesScreen extends StatelessWidget {
  final String majorName;

  const CoursesScreen({
    super.key,
    required this.majorName,
  });

  // global unique rooms
  //was "BFIN475": "Financial Investments",
  // become "BFIN4755": "Financial Investments",
  final Map<String, String> allCourses = const {
    "CENG250": "Digital Logic I",
    "CENG352L": "Digital Logic Circuits Lab",
    "CSCI250": "Introduction to Programming",
    "CSCI250L": "Introduction to Programming Lab",
    "EENG250": "Electric Circuits I",
    "EENG300": "Electric Circuits II",
    "EENG301L": "Electric Circuits Lab",
    "EENG350": "Electronic Circuits I",
    "EENG350L": "Electronic Circuits I Lab",
    "ENGG200": "Introduction to Engineering",
    "MATH210": "Calculus II",
    "MATH220": "Calculus III",
    "MATH225": "Linear Algebra with Applications",
    "MATH270": "Ordinary Differential Equations",
    "MATH310": "Probability & Statistics for Scientists & Engineers",
    "PHYS220": "Physics for Engineers",
    "CHEM200": "General Chemistry",
    "EENG304": "Biology for Biomedical Engineers",
    "EENG354": "Physiology for Biomedical Engineers",
    "EENG354L": "Physiology for Biomedical Engineers Lab",
    "EENG385": "Signals and Systems",
    "EENG388": "Electromagnetic Fields and Waves",
    "EENG400": "Electronic Circuits II",
    "EENG400L": "Electronic Circuits II Lab",
    "EENG404": "Biophysics and Bioelectricity",
    "EENG414": "Biocompatibility",
    "EENG424": "Medical Instrumentation I",
    "EENG424L": "Medical Instrumentation I Lab",
    "EENG435": "Control Systems",
    "EENG435L": "Control Systems Lab",
    "EENG474": "Medical Imaging I",
    "EENG484": "Acquisition & Microcontrollers in Biomedical Engineering",
    "EENG484L": "Acquisition and Microcontrollers in Biomedical Engineering Laboratory",
    "EENG494": "Senior Project",
    "MENG250": "Statics",
    "ARAB200": "Arabic Language and Literature",
    "CULT200": "Introduction to Arab - Islamic Civilization",
    "ENGL201": "Composition and Research Skills",
    "ENGL251": "Communication Skills",
    "ARAB220": "Creative Writing in Arabic",
    "ARTS204": "Introduction to Theater",
    "ARTS215": "History of Arts",
    "BECO210": "Introduction to Microeconomics",
    "BECO260": "Introduction to Macroeconomics",
    "BMED210": "Introduction to Community Health",
    "COMM200": "Introduction to Communication Studies",
    "COMM205": "Introduction to Western Civilization",
    "COMM220": "Rhetoric & Persuasion",
    "ENVR205": "Environment & Health",
    "HUMN200": "Community Service",
    "HUMN210": "Human Rights - Global Perspective",
    "HUMN215": "Introduction to Civic Society",
    "LANG200": "Beginners Russian",
    "LANG221": "Introduction To Italian",
    "LANG222": "Introduction To French",
    "LANG225": "Introduction To German",
    "LANG226": "Introduction to Portuguese",
    "PHED200": "Sports and Health",
    "PHIL200": "Introduction to Philosophy",
    "PHIL210": "World Religions",
    "POLS205": "World Current Affairs",
    "POLS240": "The Arab Israeli Conflict",
    "SPAN200": "Introduction to Spanish",
    "SSCI200": "Introduction to Sociology",
    "SSCI205": "Introduction to Psychology",
    "SSCI215": "Introduction to Music",
    "ENGG300": "Engineering Economics",
    "ENGG450": "Engineering Ethics and Professional Practice",
    "CSCI300": "Intermediate Programming with Objects",
    "CENG325": "Software Applications and Design",
    "CENG335": "Digital Logic II",
    "CENG375": "Introduction to Database Systems",
    "CENG380": "Microprocessors and Microcontrollers",
    "CENG400": "Computer Organization and Design",
    "CENG400L": "Microcontroller Applications Lab",
    "CENG415": "Communication Networks",
    "CENG420": "Web Programming and Technologies",
    "CENG430L": "Linux Lab",
    "CENG435": "Mobile Application Development",
    "CENG450L": "Scripting Languages Lab",
    "CENG455L": "Communication Networks Lab",
    "CENG495": "Senior Project",
    "EENG447": "Analog Communication Systems",
    "EENG467L": "Analog Communication Systems Lab",
    "CENG460": "Operating Systems",
    "CENG470": "Data Structures and Analysis of Algorithms",
    "MENG225": "Engineering Drawing & CAD",
    "EENG365": "Electrical Wiring and Installation",
    "EENG410": "Power Electronics I",
    "EENG410L": "Power Electronics I Lab",
    "EENG440": "Electric Machines I",
    "EENG460": "Introduction to Power Systems",
    "EENG482": "Electrical Systems Simulation",
    "EENG491": "Electric Machines II",
    "EENG491L": "Electric Machines II Lab",
    "EENG405": "CAD Tools for Electronics",
    "EENG459": "Electronic Systems",
    "EENG459L": "Electronic Systems Lab",
    "EENG461": "Digital Electronics",
    "EENG461L": "Digital Electronics Lab",
    "EENG370": "Industrial Electronics",
    "EENG370L": "Industrial Electronics Lab",
    "EENG492": "Electric Machines For Mechanical Engineers",
    "EENG492L": "Electric Machines For Mechanical Engineers Lab",
    "MENG300": "Dynamics",
    "MENG310": "Engineering Material Science",
    "MENG320": "Engineering Thermodynamics I",
    "MENG320L": "Engineering Thermodynamics I Lab",
    "MENG360": "Mechanics of Materials I",
    "MENG360L": "Mechanics Of Materials I Lab",
    "MENG370": "Fluid Mechanics I",
    "MENG370L": "Fluid Mechanics I Lab",
    "MENG410": "Mechanics of Materials II",
    "MENG420": "Heat Transfer",
    "MENG420L": "Heat Transfer Lab",
    "MENG430": "Mechanical Vibrations I",
    "MENG430L": "Mechanical Vibrations I Lab",
    "MENG450": "Mechanical Systems I",
    "MENG450L": "Mechanical Systems I Lab",
    "MENG470": "Internal Combustion Engines",
    "SURV251": "Introduction to Surveying Engineering",
    "SURV251L": "Introduction to Surveying Engineering Lab",
    "SURV305": "Surveying I",
    "SURV305L": "Surveying Practice I Lab",
    "SURV315": "Geology",
    "SURV325": "Cartography",
    "SURV335": "Surveying Drawing & CAD",
    "SURV355": "Surveying II",
    "SURV355L": "Surveying Practice II Lab",
    "SURV365": "Geodesy I",
    "SURV375": "Topometric Calculus I",
    "SURV385": "Computer Aided Drafting for Surveyors",
    "SURV405": "Photogrammetry",
    "SURV414": "Cadastral Surveying and Construction LAW",
    "SURV420": "Surveying application I",
    "SURV425": "Topometric Calculus II",
    "SURV435": "Theory of Measurement Errors",
    "SURV445": "Geodesy II",
    "SURV455": "Geographic Information Systems I",
    "SURV465": "Spatial Geodesy (GPS I)",
    "SURV495": "Senior Project",
    "SURV474": "Urban Planning and Land Subdivision",
    "CENG480": "Introduction to GIS",
    "IENG310L": "Industrial Engineering Field Visit",
    "IENG320": "Introduction to Environmental Engineering",
    "IENG350": "Introduction to System Engineering",
    "IENG360": "Operations Analysis Methods",
    "IENG370": "Industrial Systems Simulation",
    "IENG400": "Design and Analysis of Engineering Experiments",
    "IENG410": "Human Factors Engineering",
    "IENG420": "Industrial Engineering Information Systems",
    "IENG430": "Inventory Control",
    "IENG440": "Quality Control and Reliability",
    "IENG450": "Industrial Engineering CAD/CAM Tools",
    "IENG460": "Production Planning and Control",
    "IENG470": "Facilities Planning",
    "IENG480": "Manufacturing Processes",
    "IENG495": "Senior Project",
    "BIOC310": "Medical Biochemistry",
    "BIOL200": "General Biology I",
    "BIOL200L": "General Biology I Lab",
    "BIOL360": "Human Physiology & Anatomy",
    "BIOL360L": "Human Physiology & Anatomy Lab",
    "BIOL385": "Microbiology",
    "BIOL385L": "Microbiology Lab",
    "BMED445": "Pathophysiology",
    "CHEM200L": "General Chemistry Lab",
    "CHEM250": "Organic Chemistry I",
    "CHEM300": "Organic Chemistry II",
    "CHEM300L": "Organic Chemistry Lab",
    "PHAR200": "Introduction to Drug Information",
    "PHAR205": "Quantitative Analysis",
    "PHAR250": "Pharmacy Practice ,History & Ethics",
    "PHAR300": "Pharmaceutical Calculations",
    "PHAR400": "Medicinal Chemistry I",
    "PHAR407": "Pharmaceutical Analysis & Biotechnology",
    "PHAR407L": "Pharmaceutical/Biotechnology Lab",
    "PHAR410": "Drug Dosage Forms I",
    "PHAR415": "Professional Communications",
    "PHAR420": "Physical Pharmacy",
    "PHAR425": "Pharmacognosy & Herbal Medicine",
    "PHAR435": "Dermatology and Cosmetology",
    "PHAR450": "Medicinal Chemistry II",
    "PHAR456": "Introduction to Pharmacy Practice and Simulation",
    "PHAR460": "Pharmacy Management & Drug Marketing",
    "PHAR465": "Interpretations of Lab Data",
    "PHAR472": "Drug Dosage Form II",
    "PHAR472L": "Compounding Lab",
    "PHAR480": "Pharmacy Practice Experience I (PPEI)",
    "PHAR505": "Pharmacology I",
    "PHAR510": "Biopharmaceutics& Pharmacokinetics",
    "PHAR515": "PharmacotherapeuticsI (Neurology/Psychiatry)",
    "PHAR520": "Pharmacotherapeutics II (Pulmonary/Rheumatology)",
    "PHAR555": "Pharmacology II",
    "PHAR560": "Pharmacogenomics",
    "PHAR565": "Pharmacotherapeutics III (Cardiology/Nephrology)",
    "PHAR570": "Pharmacotherapeutics IV (Endocrinology/Dermatology)",
    "PHAR580": "Pharmacy Practice Experience II (PPE II)",
    "PHAR585": "Pharmacy Seminar",
    "PHAR606": "Non-Prescription Drugs",
    "PHAR610": "Toxicology",
    "PHAR615": "Pharmacotherapeutics V (infectious Diseases)",
    "PHAR620": "Pharmacotherapeutics VI (Hematology/Oncology)",
    "PHAR625": "Pharmacoeconomics",
    "PHAR635": "Parenteral Dosage Forms",
    "PHAR650": "Pharmacy Dispensing Practice",
    "PHAR656": "Pharmacy Law",
    "PHAR660": "Pharmacy Practice Experience III (PPE III)",
    "PHAR665": "Pharmacy Practice Experience IV(PPE IV)",
    "PHAR530": "Clinical Nutrition",
    "PHAR531": "Introduction to Epidemiology and Biostatistics",
    "PHAR532": "Special Topics: Geriatrics and Palliative Care",
    "PHAR533": "Special Topics: Ambulatory Care & First Aid",
    "PHAR534": "Special Topics: Immunization & Vaccination",
    "PHAR540": "Pharmacy Careers",
    "PHAR541": "Hospital Pharmacy",
    "PHAR590": "Industrial Pharmacy",
    "PHAR591": "Instrumental Analysis",
    "PHAR592": "Special Techniques in Antimicrobial Resistance",
    "EDUC220": "Principles of Education",
    "EDUC222": "Basics of Educational Psychology",
    "EDUC251": "Development of Children and Adolescents",
    "EDUC252": "Psychology of Learning",
    "EDUC253": "Technology Integration in Education",
    "EDUC254": "Basics of Assessment & Evaluation",
    "EDUC255": "Fundamentals of Curriculum Design",
    "EDUC320": "Fundamentals of Classroom Management",
    "EDUC322": "Instructional Methods",
    "EDUC350": "Basics of Special Education",
    "EDUC325": "Teaching Learners at Elementary Level",
    "EDUC326": "Teaching Learners at Intermediate Level",
    "EDUC351": "Methods of Teaching Oral Communication",
    "EDUC352": "Methods of Teaching Reading",
    "EDUC353": "Language Acquisition & Development",
    "EDUC354": "Understanding Research in Education",
    "EDUC422": "Teaching Practicum I",
    "EDUC425": "Assessment & Evaluation in Language Learning",
    "EDUC452": "Teaching Practicum II",
    "ENGL221": "English Grammar in Practice",
    "ENGL320": "Young Learners’ Literature",
    "ENGL321": "English Language Curriculum",
    "ENGL421": "Phonology & Phonetics",
    "CSCI200": "Introduction to Computers",
    "EDUC223": "Arts in Early Childhood",
    "EDUC263": "Music for Young Learners",
    "EDUC264": "Health and Wellness Education",
    "EDUC323": "Psychomotor Development",
    "EDUC461": "Play-Based Learning",
    "EDUC462": "Philosophical Foundations of Education",
    "ENGL361": "Academic Writing",
    "EDUC234": "Math Concepts in Basic Education",
    "EDUC330": "Teaching Math to Elementary Learners 1",
    "EDUC331": "Teaching Math with Technology",
    "EDUC360": "Teaching Math to Elementary Learners 2",
    "EDUC361": "Basics of Probability and Statistics",
    "EDUC362": "Teaching Numeracy and Arithmetic",
    "EDUC430": "Teaching Geometry and Measurement",
    "EDUC431": "Problem Solving in Basic Education",
    "EDUC332": "Elementary Level Science Concepts",
    "EDUC363": "Teaching Sciences in Basic Education",
    "EDUC364": "Fundamentals of Physical Sciences",
    "EDUC365": "Teaching Sciences with Technology",
    "EDUC432": "Basics of Earth Sciences",
    "EDUC433": "Inquiry-Based Science Education",
    "ENGL330": "Basics of English Literature",
    "ENGL331": "Introduction to Linguistics",
    "ENGL332": "Syntax of the English Language",
    "EDUC324": "Curriculum for Early Childhood Education",
    "EDUC329": "Assessment & Evaluation in ECE",
    "EDUC424": "Math & Science for Young Learners",
    "ARAB210": "Technical Writing: Arabic",
    "ARAB211": "Editing & Proofreading: Arabic",
    "ENGL207": "Technical Writing: English",
    "FREN210": "Intermediate French: A2-2",
    "FREN300": "Intermediate French: A2-3",
    "FREN310": "Upper French: B1-1",
    "FREN311": "Upper French: B1-2",
    "SPAN210": "Spanish level 2",
    "SPAN300": "Spanish level 3",
    "TRNS300": "Introduction to Translation EN-AR",
    "TRNS301": "Introduction to Translation AR-EN",
    "TRNS314": "Introduction to Translation FR-AR",
    "ENGL415": "Editing & Proofreading: English",
    "FREN400": "Upper French: B1-3",
    "FREN410": "Upper French: B2- FLE",
    "TRNS302": "Media Translation",
    "TRNS310": "Scientific and Technical Translation",
    "TRNS311": "Translation of UN Documents",
    "TRNS312": "On-Sight Interpretation",
    "TRNS400": "Economic Translation",
    "TRNS401": "Consecutive Interpretation",
    "TRNS402": "Literary Translation",
    "TRNS403": "Translation of Various Domains FR-AR/ AR-FR",
    "TRNS404": "Introduction to Translation Studies",
    "TRNS410": "Medical Translation",
    "TRNS411": "Translation of Legal & Official Documents",
    "TRNS412": "Translation Senior Project",
    "TRNS413": "Simultaneous Interpretation",
    "BACC200": "Financial Accounting",
    "BECO250": "Introduction to Microeconomics",
    "BECO301": "Introduction to Macroeconomics",
    "BFIN250": "Introduction to Finance",
    "BMGT200": "Introduction to Business Management",
    "BMGT315": "Human Resource Management",
    "BMIS250": "Management Information Systems",
    "BMKT250": "Marketing Theory and Principles",
    "BMTH210": "Business and Managerial Math",
    "BSTA205": "Introduction to Business Statistics",
    "BACC250": "Managerial Accounting",
    "BACC330": "Intermediate Financial Accounting I",
    "BACC340": "Advanced Managerial Accounting",
    "BACC350": "Accounting Information Systems and Applications",
    "BACC370": "Intermediate Financial Accounting II",
    "BACC420": "Tax Accounting",
    "BACC430": "Auditing and Fraud Prevention",
    "BACC497": "Advanced Accounting",
    "BACC499": "Senior Project In Accounting",
    "BMGT350": "Introduction to Business Law",
    "BMGT351": "Organizational Behavior",
    "BMGT401": "Business Ethics",
    "BMGT491": "Global Strategic Management",
    "BMGT496": "Research Methods for Business",
    "BMIS401": "Operations Management",
    "BECO305": "Intermediate Microeconomics",
    "BECO306": "Labor Economics and Market Structures",
    "BECO350": "Intermediate Macroeconomics",
    "BECO385": "Econometrics",
    "BECO401": "Growth Models and Policy",
    "BECO430": "International Economics and Trade",
    "BECO470": "Economics of Money and Banking",
    "BECO499": "Senior Project in Economics",
    "BFIN310": "Financial Reporting and Analysis",
    "BFIN340": "International Finance",
    "BFIN350": "Financial Management",
    "BFIN370": "Modern Banking and Risk Management",
    "BFIN425": "Introduction to FinTech",
    "BFIN435": "Financial Markets and Institutions",
    "BFIN475": "Investment Analysis",
    "BFIN499": "Senior Project In Finance",
    "BHTM305": "Introduction to Hospitality & Tourism Industry",
    "BHTM311": "Lodging Management",
    "BHTM351": "Restaurant Management",
    "BHTM352": "Business Etiquette & Protocol",
    "BHTM425": "Food and Beverage Cost Control",
    "BHTM445": "Conventions and Meetings Management",
    "BHTM495": "Revenue Management",
    "BHTM499": "Senior Project In Hotel and Tourism Management",
    "BMGT320": "Innovation Management",
    "BMGT325": "Decision Making Management",
    "BMGT375": "Training and Development Management",
    "BMGT385": "Total Quality Management",
    "BMGT402": "Leadership Principles",
    "BMGT405": "Managing Business Governance",
    "BMGT497": "Managing Entrepreneurship",
    "BMGT499": "Senior Project In Management",
    "BMIS301": "E-Business",
    "BMIS302": "Database Management",
    "BMIS351": "Business Telecommunication",
    "BMIS352": "Systems Analysis and Design",
    "BMIS402": "Business Intelligence Systems",
    "BMIS403": "Programming Fundamentals",
    "BMIS480": "Knowledge Management",
    "BMIS499": "Senior Project In Management Information Systems",
    "BMKT303": "Consumer Behavior",
    "BMKT340": "Global Marketing",
    "BMKT355": "Digital Marketing",
    "BMKT380": "Strategic Brand Management",
    "BMKT401": "Integrated Marketing Communication",
    "BMKT405": "Sales and Customer Service Management",
    "BMKT497": "Retailing & Merchandising Management",
    "BMKT499": "Senior Project In Marketing",
    "BFIN300": "Business Finance",
    "BMGT300": "Introduction to Business Law",
    "BMGT340": "Organizational Behavior",
    "BMGT360": "Research Methods for Business",
    "BMGT380": "Business Ethics",
    "BMGT470": "Total Quality Management",
    "BMIS300": "Management Information Systems",
    "BMIS355": "Quantitative Methods of Business Decisions",
    "BMIS400": "E-Business",
    "IMGT390": "Strategic Negotiations",
    "WACC210": "Introduction to International Accounting",
    "WACC260": "Basics of International Financial Reporting Standards/ International Accounting Standards",
    "WECO210": "Basics of International Economics",
    "WMGT315": "Leadership Development",
    "WMGT365": "Organization",
    "WMGT430": "Basics in International Business Management",
    "WMGT490": "Business Strategy and Controlling in International Business",
    "WMGT491": "Major Requirement 1",
    "WMGT492": "Major Requirement 2",
    "WMGT497a": "Strategic Management",
    "WMGT497b": "Internationalization Strategies",
    "WMKT300": "Marketing Basics",
    "WMKT400": "Internet Marketing",
    "WICI200": "Intercultural Issues",
    "WULT200": "European Studies",
    "BACC400": "Accounting Information Systems and Applications",
    "BACC450": "Lebanese Accounting Practices",
    "BECO340": "Intermediate Macroeconomics",
    "BECO365": "Growth Models and Policy",
    "BECO400": "Labor Economics and Market Structures",
    "BFIN360": "Financial Reporting and Analysis",
    "BFIN400": "Financial Modeling",
    "BFIN430": "International Banking and Finance",
    "BFIN440": "Banking Operations",
    "BFIN470": "Financial Markets and Institutions",
    "BFIN4755": "Financial Investments",
    "BHTM315": "Business Etiquette & Protocol",
    "BMGT475": "Leadership Principles",
    "BMIS310": "Business Telecommunications",
    "BMIS320": "Data Management",
    "BMIS370": "System Analysis and Design",
    "BMIS375": "Programming Fundamentals",
    "BMIS497": "Business Intelligence Systems",
    "BMKT310": "Digital Marketing",
    "BMKT315": "Integrated Marketing Communication",
    "BMKT350": "Consumer Behavior",
    "BMKT360": "Market Research Methods",
    "BMKT420": "Customer Service Management",
    "IMGT430": "International Business Management",
    "IMGT497": "Managing Entrepreneurship",
    "ADVR300": "Advertising Theory & Practice",
    "ARTS350": "Photography",
    "COMM225": "Workshop",
    "COMM265": "Performance Theory & Practice",
    "COMM285": "Theories of Perception",
    "COMM305": "Artificial Intelligence and Mass Media",
    "GDES270": "Design Software I",
    "JORN285": "Travel Journalism",
    "PREL300": "Public Relations Principles & Concepts",
    "ADVR348": "Advertising Pitching",
    "ADVR350": "Advertising Copywriting",
    "ADVR370": "Psychology of Advertising",
    "ADVR390": "Branding and Corporate Identity",
    "ADVR410": "Advertising & Sales Promotion",
    "ADVR420": "New Media in advertising",
    "ADVR430": "Advertising Storyboard",
    "ADVR460": "Advertising Creativity",
    "ADVR485": "Advertising Campaign Design",
    "ADVR495": "Senior Study in Advertising",
    "COMM300": "Media Laws & Ethics",
    "COMM310": "Research Methods in Communication Arts",
    "COMM320": "Radio-TV Announcing",
    "COMM330": "Media Planning & Audience Analysis",
    "COMM400": "Media Management",
    "PREL455": "Public Speaking",
    "RATV316": "Mobile Media",
    "RATV370": "Writing for Radio and TV",
    "JORN200": "News Writing & Reporting",
    "JORN370": "Arabic News Writing & Reporting",
    "JORN375": "Journalism Workshop",
    "JORN380": "Web Journalism",
    "JORN385": "Citizen Journalism",
    "JORN410": "News Production",
    "JORN440": "Reporting of Public Affairs",
    "JORN450": "Investigative Journalism",
    "JORN495": "Senior Study in Journalism",
    "RTVF425": "Documentary Making",
    "PREL360": "Public Relations Practice & Analysis",
    "PREL375": "Specialized Writing in Public Relations",
    "PREL380": "Communication Tools in Public Relations",
    "PREL405": "Public Relations Event management",
    "PREL420": "Crisis Communication in PR",
    "PREL430": "Public Relations Campaign",
    "PREL445": "Critical Inquiry & Public Relations",
    "PREL450": "Public Relations Workshop",
    "PREL465": "Public Relations and Brand Management",
    "PREL495": "Senior Study in Public Relations",
    "RATV230": "Radio-TV Workshop II",
    "RATV315": "Television Production",
    "RATV425": "TV Directing",
    "RATV430": "Radio Production",
    "RATV440": "Digital media production",
    "RATV495": "Senior Study in Radio and TV",
    "COMM325": "Animation Software",
    "RTVF340": "Script Writing",
    "RTVF410": "Art of Film",
    "CHEM260": "Analytical Chemistry",
    "CHEM260L": "Analytical Chemistry Lab",
    "BIOC250": "Biochemistry I (General)",
    "BIOL275": "Cell and Molecular Biology",
    "BIOL275L": "Cell and Molecular Biology Lab",
    "PHYS205": "General Physics for Scientists",
    "CHEM310": "Physical Chemistry I",
    "BIOL365": "Genetics",
    "BIOC350": "Biochemistry II (Intermediary)",
    "BIOC350L": "Biochemistry II Lab",
    "BIOC400": "Biochemistry III (Protein Structure & Function)",
    "BIOC405": "Enzymology",
    "BIOC445": "Biotechnology",
    "BIOC450": "Advanced Lab Techniques in Biochemistry",
    "BIOC485": "Modern Topics in Biochemistry",
    "BIOL490": "Seminar",
    "BMED450": "Clinical Chemistry",
    "BMED450L": "Clinical Chemistry Lab",
    "CHEM440": "Advanced Physical Chemistry",
    "MATH245": "Statistics for Health Sciences",
    "BIOL250": "General Biology II",
    "BIOL250L": "General Biology II Lab",
    "CHEM255": "Basic Organic Chemistry",
    "CHEM255L": "Basic Organic Chemistry Lab",
    "BMED205": "Biophysics",
    "BIOL315": "Animal Behavior",
    "BIOL315L": "Animal Behavior Project",
    "BIOL335": "Ecology",
    "BIOL335L": "Ecology Lab",
    "BIOL375": "Plant Physiology",
    "BIOL375L": "Plant Physiology Lab",
    "BIOL425": "Immunology",
    "BIOL435": "Developmental Biology",
    "BIOL435L": "Developmental Biology Lab",
    "BIOL450": "Modern Topics in Biology",
    "BIOL485": "Neurobiology",
    "BMED360": "Hematology",
    "BMED360L": "Hematology LAB",
    "BMED370": "Parasitology",
    "BMED370L": "Parasitology Lab",
    "BMED425": "Serology and Blood Banking",
    "BMED425L": "Serology and Blood Banking Lab",
    "BMED430": "Medical Microbiology",
    "BMED430L": "Medical Microbiology Lab",
    "BMED460": "Histopathology",
    "BMED470": "Clinical Mycology and Virology",
    "BMED475": "Clinical Hematology and Hemostasis",
    "BMED485": "Clinical Assessment and Techniques",
    "BMED490": "Medical Laboratory Management and Quality Assurance",
    "MEDL399": "Medical Laboratory Internship I",
    "MEDL499": "Medical Laboratory Internship II",
    "PHYS250": "Thermodynamic and Waves",
    "PHYS280": "Electricity and Magnetism",
    "CHEM310L": "Physical Chemistry I Lab",
    "CHEM350": "Organic Chemistry III",
    "CHEM350L": "Organic Chemistry Lab III Lab",
    "CHEM370": "Inorganic Chemistry I",
    "CHEM370L": "Inorganic Chemistry I Lab",
    "CHEM400": "Inorganic Chemistry II",
    "CHEM410": "Structure Determination of Compounds",
    "CHEM420": "Industrial Chemistry",
    "CHEM430": "Instrumental Chemistry",
    "CHEM465": "Environmental Chemistry",
    "CHEM480": "Senior Project in Chemistry",
    "CHEM490": "Modern Topics in Chemistry",
    "CSCI205": "Computer Science Overview",
    "MATH260": "Discrete Mathematics",
    "MATH260L": "Discrete Mathematics Lab",
    "CSCI300L": "Intermediate Programming with Objects Lab",
    "CSCI335": "Database Systems",
    "CSCI342": "Fundamentals of Networking Technologies",
    "CSCI373": "Robotics Design & Coding",
    "CSCI378": "Data Structures and Algorithms",
    "CSCI380": "Software Engineering",
    "CSCI390": "Web Programming",
    "CSCI405": "Computer Organization and Architecture",
    "CSCI430": "Operating Systems",
    "CSCI430L": "Operating Systems Lab",
    "CSCI450": "Theory of Computation",
    "CSCI451": "Parallel Processing",
    "CSCI475": "Artificial Intelligence",
    "CSCI490": "Information System Development",
    "CSCI499": "Internship",
    "CSIT205": "Introduction to Information Technology",
    "MATH257": "Elements of Discrete Mathematics",
    "CSIT381": "Microcomputer Support",
    "CSCI362": "Network Security",
    "CSCI392": "Computer Networks",
    "CSIT415": "System and Network Administration",
    "CSIT430": "Internetworking and Routing Protocols",
    "CSIT482": "Human-Computer Interaction",
    "CSIT499": "Professional development in IT",
    "NUTR250": "Basic Nutrition",
    "FDSC300": "Technology of Food Products",
    "FDSC300L": "Technology of Food Products Lab",
    "FDSC355": "Food Microbiology II",
    "FDSC355L": "Food Microbiology II Lab",
    "FDSC360": "Crop Production Attributes to Quality",
    "FDSC365": "Animal Production Attributes to Quality",
    "FDSC370": "Food Chemistry",
    "FDSC415": "Dairy Technology",
    "FDSC420": "Food Processing",
    "FDSC425L": "Food Processing Lab",
    "FDSC435": "Food Toxicants and Additives",
    "FDSC445": "Food Quality management and HACCP",
    "FDSC455": "Meat, Fish and Poultry Technology",
    "FDSC460": "Food Service Management",
    "FDSC475": "Food Engineering",
    "FDSC490": "Modern Topics In Food Science",
    "FDSC498": "Supervised Training in Food Industries",
    "ARTS200": "Foundation Drawing I",
    "ARTS210": "Color Theory - Painting",
    "ARTS250": "Foundation Drawing II",
    "ARTS260": "Design Fundamentals - 2D",
    "ARTS270": "Design Fundamentals - 3D",
    "ARTS320": "Rendering and Perspective Techniques",
    "GDES300": "Typography I",
    "GDES315": "History of Graphic Design",
    "GDES345": "Graphic Design Studio I",
    "GDES350": "Typography II & Art of Calligraphy",
    "GDES365": "Illustration II - Story Board",
    "GDES370": "Graphic Design Software II",
    "GDES394": "Graphic Design Studio II",
    "GDES421": "Web Page Design",
    "GDES441": "Packaging",
    "GDES445": "Graphic Design Studio III",
    "GDES450": "Advanced Animation",
    "GDES485": "Professional Practice",
    "GDES495": "Graphic Design Senior Project",
    "IDES300": "Architectural Drawing",
    "IDES310": "Materials - Techniques and Building Codes",
    "IDES330": "CAD I",
    "IDES345": "Interior Design Studio I",
    "IDES360": "Lighting and HVAC",
    "IDES370": "Furniture History and Design",
    "IDES380": "CAD II",
    "IDES386": "Rendering & Adobe Photoshop",
    "IDES394": "Interior Design Studio II",
    "IDES400": "Architectural Modeling",
    "IDES420": "Landscape Design",
    "IDES430": "Computer Rendering for Interior Design",
    "IDES445": "Interior Design Studio III",
    "IDES480": "Professional Practice",
    "IDES495": "Interior Design Senior Project",
    "PHYS210": "Mechanics",
    "MATH305": "Programming Languages for Scientist",
    "MATH315": "Advanced Linear Algebra",
    "MATH330": "Partial Differential Equations",
    "MATH345": "Introduction to Real Analysis",
    "MATH365": "Abstract Algebra",
    "MATH375": "Numerical Methods for Scientists & Engineers",
    "MATH380": "Complex Variables",
    "MATH385": "Introduction to Topology",
    "MATH405": "Number Theory",
    "MATH420": "Differential Geometry",
    "MATH455": "Mathematical Analysis",
    "MATH490": "Modern Topics in Algebra",
    "MATH492": "Mathematical Seminar",
    "PHYS300": "Mathematical Physics",
    "PHYS330": "Electromagnetic Fields and Waves I",
    "PHYS340": "Modern Physics",
    "PHYS340L": "Atomic Physics Lab",
    "PHYS350": "Physical Optics",
    "PHYS350L": "Physical Optics Lab",
    "PHYS360": "Analytical Mechanics",
    "PHYS380": "Electromagnetic Fields and Waves II",
    "PHYS420": "Quantum Mechanics",
    "PHYS430": "Thermal Physics I",
    "PHYS450": "Solid State Physics",
    "PHYS470": "Advanced Quantum Mechanics",
    "PHYS480": "Thermal Physics II",
    "PHYS490": "Physics Seminar",
    "NUTR315": "Human Nutrition and Metabolism",
    "NUTR351": "Nutritional Assessment and Counseling",
    "NUTR400": "Nutrition Through Life Span",
    "NUTR411": "Therapeutic Nutrition",
    "NUTR440": "Obesity & Regulation of Body Weight",
    "NUTR450": "Community Nutrition",
    "NUTR475": "Inborn Errors of Metabolism",
    "NUTR485": "Selected Topics in Clinical Nutrition",
    "NUTR490": "Nutrition Seminar",
    "PHYS250L": "Thermodynamic and Waves Lab",
    "PHYS280L": "Electricity and Magnetism Lab",
  };

  // which major can access which courses
  final Map<String, List<String>> majorCourses = const {
    "Information Technology": [
      "CSCI300",
      "CSC320",
      "CSC401",
      "CSC370",
      "CSC450",
    ],

    "Computer Science": [
      "CSC210",
      "CSC320",
      "CSC350",
      "CSC450",
    ],

    "Computer Engineering": [
      "CSC210",
      "CSC350",
      "CSC370",
    ],
  };

  @override
  Widget build(BuildContext context) {
    final isDark =
        Theme.of(context).brightness == Brightness.dark;

    final List<String> courseCodes =
        majorCourses[majorName] ?? [];

    return Scaffold(
      appBar: AppBar(
        title: Text("$majorName Courses"),
      ),
      body: Padding(
        padding: EdgeInsets.all(16.w),
        child: ListView.builder(
          itemCount: courseCodes.length,
          itemBuilder: (context, index) {
            final code = courseCodes[index];
            final courseName =
                allCourses[code] ?? "Unknown Course";

            return Padding(
              padding: EdgeInsets.only(bottom: 15.h),
              child: Container(
                decoration: BoxDecoration(
                  color:
                  isDark ? Colors.white10 : Colors.white,
                  borderRadius:
                  BorderRadius.circular(20.r),
                  boxShadow: const [
                    BoxShadow(
                      color: Colors.black12,
                      blurRadius: 8,
                    )
                  ],
                ),
                child: ListTile(
                  leading: const CircleAvatar(
                    child: Icon(Icons.book),
                  ),
                  title: Text(courseName),
                  subtitle: Text(code),
                  trailing:
                  const Icon(Icons.arrow_forward_ios),
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (_) => ChatScreen(
                          title: courseName,
                          roomId: code, // مهم: هذا يوحد الغرفة
                        ),
                      ),
                    );
                  },
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}